# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b293d5cd147281fb713817e1b16fb087f8230478bfe751887db77e5cc731a642b78019352b07a7fe6ef4b03a5e28aa7aafb015e8eec4ad0d928cdb5d9be06eb

test:
  secret_key_base: 5edbe6efd8f86e89e35b59c8a2cb4da03f3805cbf26b423a51a9eaf23581ade7ba98d84d8388f7a0ca3439be45c4de65f85d6b28bddd9b1e173ba99cbc67c3c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
